gcc -O4 -L/usr/local/lib -o generateGaussianNoise.o generateGaussianNoise.c alloc.c ppmfile.c matrices.c qualitymetrics.c -lgsl -lgslcblas -lm
gcc -O4 -L/usr/local/lib -o denoise_color_dynamicK.o denoise_color_dynamicK.c alloc.c ppmfile.c matrices.c qualitymetrics.c dctfilter.c rgb_ycbcr.c -lgsl -lgslcblas -lm
gcc -O4 -L/usr/local/lib -o denoise_color_dynamicK_KLT.o denoise_color_dynamicK_KLT.c alloc.c ppmfile.c matrices.c qualitymetrics.c dctfilter.c rgb_ycbcr.c -lgsl -lgslcblas -lm
gcc -O4 -L/usr/local/lib -o denoise_color_hosvd_dynamicK_KLT.o denoise_color_hosvd_dynamicK_KLT.c alloc.c ppmfile.c matrices.c matrix3d.c qualitymetrics.c dctfilter.c rgb_ycbcr.c -lgsl -lgslcblas -lm
