gcc -O4 -L/usr/local/lib -o denoise_hosvd_dynamicK.o denoise_hosvd_dynamicK.c alloc.c pgmfile.c matrices.c qualitymetrics.c dctfilter.c matrix3d.c -lgsl -lgslcblas -lm
gcc -O4 -L/usr/local/lib -o denoise_hosvd_dynamicK_wiener.o denoise_hosvd_dynamicK_wiener.c alloc.c pgmfile.c matrices.c qualitymetrics.c dctfilter.c matrix3d.c -lgsl -lgslcblas -lm
gcc -O4 -L/usr/local/lib -o denoise_DCT_dynamicK.o denoise_DCT_dynamicK.c alloc.c pgmfile.c matrices.c qualitymetrics.c dctfilter.c matrix3d.c -lgsl -lgslcblas -lm
gcc -O4 -L/usr/local/lib -o denoise_dynamicK.o denoise_dynamicK.c alloc.c pgmfile.c matrices.c qualitymetrics.c dctfilter.c hyptest.c -lgsl -lgslcblas -lm
gcc -O4 -L/usr/local/lib -o denoise_dynamicK_nonrobust.o denoise_dynamicK_nonrobust.c alloc.c pgmfile.c matrices.c qualitymetrics.c dctfilter.c hyptest.c -lgsl -lgslcblas -lm
gcc -O4 -L/usr/local/lib -o generateNoise.o generateNoise.c alloc.c pgmfile.c matrices.c qualitymetrics.c -lgsl -lgslcblas -lm
gcc -O4 -L/usr/local/lib -o bestpatchsize_denoise_dynamicK.o bestpatchsize_denoise_dynamicK.c alloc.c pgmfile.c matrices.c qualitymetrics.c dctfilter.c hyptest.c -lgsl -lgslcblas -lm
gcc -O4 -L/usr/local/lib -o bestsigma_denoise_dynamicK.o bestsigma_denoise_dynamicK.c alloc.c pgmfile.c matrices.c qualitymetrics.c dctfilter.c hyptest.c -lgsl -lgslcblas -lm
